---
title: "Analysis for RVA 3"
author: "Daniel P"
output: html_document
---

Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(mc.cores=12)

path_to_project_directory <- "~/projects/RVA_3/"
path_to_s22 <- "~/projects/spring_2022_study/"
path_to_rva <- "~/projects/RVA/"

stan_model_dir<- paste0(path_to_project_directory,"code/stan_models/")
model_out_dir <- paste0(path_to_project_directory,"output/results/stan_model_fits/")

#load custom functions
source(paste0(path_to_s22,"code/functions/fit_stan_model.R")) 
source(paste0(path_to_s22,"code/functions/s22_utilities.R")) 
source(paste0(path_to_s22,"code/functions/stan_utilities.R"))
source(paste0(path_to_rva,"code/functions/rva_utilities.R"))
source(paste0(path_to_project_directory,"code/functions/rva3_utilities.R")) 

library(tidyverse)
library(cmdstanr)
library(bayesplot)
library(abind)
library(sigmoid)
library(posterior)
```

Read in data, run through QC
```{r}
trials <- read.csv(paste0(path_to_project_directory,"analysis_data/trial_level_data_all_subs_2025-03-06_19_00_16.812019.csv"))
subs <- read.csv(paste0(path_to_project_directory,"analysis_data/sub_level_data_all_subs_2025-03-06_19_00_16.812019.csv"))

sub_hard_fail <- subs %>% filter(att_checks_passed < 3 |
                                 answers_incorrect > 3 |
                                 sd_valrat < .04 |
                                 sd_probrat < .05 |
                                 valrat_skipped_percent > .15 |
                                 probrat_skipped_percent > .15 |
                                 trials_completed < 96)

#count the number of soft QC cutoffs each subject meets
subs$softs <- 0
for(i in 1:nrow(subs)){
  subs$softs[i] <- length(which(c(subs$att_checks_passed[i] == 3,subs$answers_incorrect[i] == 3,
                                  subs$valrat_skipped_percent[i] > .10,
                                  subs$sd_probrat[i] < .07, subs$probrat_skipped_percent[i] > .10)))
}

sub_soft_fail <- filter(subs,softs >= 2) #identify those who meet more than 2 soft cutoffs

subs_to_exclude <- unique(c(sub_hard_fail$id,sub_soft_fail$id)) #get subjects who failed either set of criteria

#clean data
trials <- trials %>% filter(!(id %in% subs_to_exclude))
subs <- subs %>% filter(!(id %in% subs_to_exclude))

length(subs_to_exclude)/(nrow(subs)+length(subs_to_exclude)) #get percent excluded
```

Data transformations
```{r}
trials <- add_sub_indices(trials) #add subject indices to the df. These will match the indices used in Stan.
trials <- add_probe_number(trials,newcol="vrat_number",val_col="val_rat") #add valence rating number
trials <- add_probe_number(trials,newcol="prat_number",val_col="prob_rat") #add probability rating number
# Create mean-centered block and trial numbers
trials <- mutate(trials, bl_cent = block - mean(block), tr_cent = trial_blk - mean(trial_blk)) 

# Add fractal indexes
trials <- trials %>% mutate(frac_ix = case_when(
                      frac_img == 1 ~ 1,
                      frac_img == 9 ~ 2,
                      frac_img == 3 ~ 3,
                      frac_img == 5 ~ 4,
                      )) %>%
                    mutate(alt_frac_ix = case_when(
                      frac_ix == 1 ~ 2,
                      frac_ix == 2 ~ 1,
                      frac_ix == 3 ~ 4,
                      frac_ix == 4 ~ 3
                    ))
```

How many subjects said they experienced significant emotion during the task?
```{r}
sig_emot <- subs$sig_emot[!is.na(subs$sig_emot)]
sum(sig_emot == "Yes")/nrow(subs)
```

```{r}
subs$age <- as.numeric(subs$age)
mean(subs$age,na.rm=T)
median(subs$age,na.rm=T)
sd(subs$age,na.rm=T)
```

```{r}
sum(subs$gender=="Male",na.rm=T)
```

```{r}
sum(subs$gender=="Female",na.rm=T)
```

```{r}
sum(subs$gender=="Non-binary",na.rm=T)
```

# Preregistered analyses

Fit preregistered model
```{r}
prereg <- fit_stan_model(stan_file=paste0(stan_model_dir,"prereg_rva3.stan"),
                                   model_out_dir=model_out_dir,
                                   raw_data=trials,
                                   study = "rva3")
```

Review results
```{r}
prereg$diagnostics
```

```{r}
view(filt_sum(prereg$sum,"mu"))
view(filt_sum(prereg$sum,"sigma"))
```

Get r-sq for probability ratings
```{r}
pp_prereg <- get_draws("prereg_rva3",model_out_dir=model_out_dir,vars=c("prob_pred"))
ps_prereg <- get_draws("prereg_rva3",model_out_dir=model_out_dir,vars=c("prob_sigma"))
prob_rsq_prereg <- mcmc_rsq(pp_prereg,ps_prereg,print_plot=FALSE)
prob_rsq_prereg$sum['median']
```

Get r-sq for valence ratings
```{r}
vp_prereg <- get_draws("prereg_rva3",model_out_dir=model_out_dir,vars=c("val_pred"))
vss_prereg <- get_draws("prereg_rva3",model_out_dir=model_out_dir,vars=c("val_sigma_sigma"))
vs_prereg <- apply(vss_prereg,c(1,2,3),half_normal_mean)
val_rsq_prereg <- mcmc_rsq(vp_prereg,vs_prereg,print_plot=FALSE)
val_rsq_prereg$sum[['median']]
```

Get regression effects
```{r}
prereg_eff <- get_draws("prereg_rva3",model_out_dir=model_out_dir,vars=c("wx_mu"))
create_interval_plot(arr = prereg_eff, xmin = -0.02, xmax = .01,names=c("wx_mu[3]","wx_mu[2]","wx_mu[1]"))
mean(prereg_eff[,,"wx_mu[2]"] < prereg_eff[,,"wx_mu[3]"])
quantile(prereg_eff[,,"wx_mu[2]"] - prereg_eff[,,"wx_mu[3]"],c(.025,.5,.975))
```

```{r}
set.seed(7)
rew <- c(1,0)
rpe <- c(0.71,-0.71)
dvec_mat <- cbind(rew,rpe) #turn into matrix


eff_dims <- abind(prereg_eff[,,c("wx_mu[1]")],prereg_eff[,,c("wx_mu[2]")] - prereg_eff[,,c("wx_mu[3]")],along=3)
vec_ws_prereg <- apply(eff_dims,c(1,2),vec_optim,dvec=dvec_mat,init_pars=c(0,0)) #get vector weights

vec_ws_prereg_org <- aperm(vec_ws_prereg,c(2,3,1)) #rearrange dimensions
dimnames(vec_ws_prereg_org)[[3]] <- c("rew","rpe") #name appropriately
create_interval_plot(vec_ws_prereg_org,names = c("rpe","rew"),xmin = -.012, xmax = .01)
median(vec_ws_prereg_org[,,"rew"])
median(vec_ws_prereg_org[,,"rpe"])
```



